### ISSUE TITLE
Cannot create Smartsheet - java.lang.NoSuchFieldError: No field INSTANCE 

### ISSUE THREAD

**Issue by soommy12** [smartsheet-platform/smartsheet-java-sdk#90]
Hello!
While following your example during `Smartsheet` initialization:

`Smartsheet ss = SmartsheetFactory.createDefaultClient(accessToken);`

I am getting this error:
`java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)`

It seems that library is using the older version of HttpClient. I've met [this ](https://stackoverflow.com/questions/32793830/error-while-trying-to-use-an-api-java-lang-nosuchfielderror-instance)StackOverflow question where the problem is the same but still not solved. Maybe description there will be more helpful.

Can you please give me the solution or any workaround? Thanks!

**Comment by timwellswa** [comment]
Hi, can you tell me what version of the Smartsheet SDK you are using? Can you also paste the full exception stack trace complete with line numbers?

**Comment by soommy12** [comment]
Yes, sure. The library **version is 2.2.5.** I think it is worth noting that I using the library on Android API 25. The whole stack trace:

`07-22 21:14:10.887 28783-28783/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.bgn.smtest, PID: 28783
                                                   java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
                                                       at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
                                                       at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955)
                                                       at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:58)
                                                       at com.smartsheet.api.internal.SmartsheetImpl.<init>(SmartsheetImpl.java:281)
                                                       at com.smartsheet.api.internal.SmartsheetImpl.<init>(SmartsheetImpl.java:260)
                                                       at com.smartsheet.api.SmartsheetFactory.createDefaultClient(SmartsheetFactory.java:54)
                                                       at com.bgn.smtest.MainActivity.onCreate(MainActivity.java:64)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-22 21:14:16.911 28783-28792/com.bgn.smtest E/System: Uncaught exception thrown by finalizer
07-22 21:14:16.912 28783-28792/com.bgn.smtest E/System: java.lang.NullPointerException: Attempt to invoke interface method 'void com.smartsheet.api.internal.http.HttpClient.close()' on a null object reference
                                                                        at com.smartsheet.api.internal.SmartsheetImpl.finalize(SmartsheetImpl.java:312)
                                                                        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                        at java.lang.Thread.run(Thread.java:761)
`

**Comment by soommy12** [comment]
Any ideas about this?

**Comment by brettlemoine** [comment]
Hi soommy12 -

It looks like you need to add Jackson dependencies to your POM, I think that's missing from the sample project.

Add this to the POM and it should work:

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.7.4</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.7.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.7.4</version>
        </dependency>

**Comment by soommy12** [comment]
Hi @brettlemoine , thank you for your answer. When it comes to **gradle**, what should I put there? I am not using POM in Android.

**Comment by soommy12** [comment]
Unfortunately, when I added this dependency into gradle:
`compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.6.2'` (there is no newer version) the console gives me still the same error.

**Comment by brettlemoine** [comment]
Ah, sorry about that.  I'm not super familiar with gradle but gimme a sec.

**Comment by brettlemoine** [comment]
I think you need *both*.  That's what got it for me.  Have you tried adding both core and databind?

compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.6.2'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.6.2'

(also, I was using 2.7.4 but I don't see a reason 2.6.2. wouldn't work)

**Comment by brettlemoine** [comment]
Looking at this again, you may need to add a reference to the jackson-annotations as well.

**Comment by soommy12** [comment]
I added the `jackson-annotations` too but the app crashes with the same error.

**Comment by soommy12** [comment]
I think that the problem is `'org.apache.httpcomponents',` the library which you added in your POM file as a dependency. Android itself provide `Httpclient` that is why I didn't attach it. When I tried though gradle told me about conflicts which I was aware of. Any ideas on how to solve the issue?

**Comment by brettlemoine** [comment]
Sorry for the delay.

Ah geeze.  Untangling dependency problems is easily one of my least favorite parts of Java development.  Let me see if I can figure this out!  We may need @timwellswa as well.

**Comment by brettlemoine** [comment]
Talking to another dev here, it looks like Jackson is using an incompatible version of httpcomponents under the hood.  We could **not** get it working at all with 2.6.2 but we could with 2.7.4.

**Comment by soommy12** [comment]
Sounds more real now. When can I expect a fix?

**Comment by brettlemoine** [comment]
I can't actually repackage it unfortunately; I think we need @timwellswa to speak to that.  I can tell you the C# package had similar external dependencies - couldn't install it without installing Newtonsoft.JSON first.

**Comment by soommy12** [comment]
Ok, I understand that. The thing is that my project is mostly based on integration with the smartsheet. I need to know if the fix will be done soon because otherwise, I will have to do my own API connection with needed endpoints.

**Comment by timwellswa** [comment]
I am happy to take a look at this but I can tell you with my current backlog it won't be quickly. Feel free to clone the SDK from source though and modify to fit your requirements. Seems like that would be faster that rolling your own.

**Comment by soommy12** [comment]
HI @timwellswa , so, to sum up: there is no deadline for the fix. Unfortunately, without it, the library is unusable in Android at this moment.

**Comment by timwellswa** [comment]
This is not at all timely, but you can take a look at PR #102 and PR #105 regarding the use of the SDK on Android. Refer to the Android section in [ADVANCED.md](https://github.com/smartsheet-platform/smartsheet-java-sdk/blob/master/ADVANCED.md)
